"""Maintain a bounded intent-to-page map; no invented traffic or difficulty metrics."""
from pathlib import Path
import csv,json
from seo_pages import CONTENT, category_path, product_path
ROOT=Path(__file__).parent
rows=[]
def add(keywords,path,intent,kind,coverage,competitors,priority='P2',links='',answer='Answer the task before listing options'):
    for keyword in keywords:
        rows.append({'Keyword':keyword,'Search intent':intent,'Competitor coverage':competitors,'AI Tools Zone coverage':coverage,'Recommended page':path,'Priority':priority,'Content type':kind,'Internal links':links,'Schema':'Product + Offer + BreadcrumbList + WebPage' if kind=='product' else 'WebPage + BreadcrumbList; ItemList when listing products','AEO opportunity':answer,'GEO/entity opportunity':'AI Tools Zone; independent marketplace; Pakistan; PKR; confirmed WhatsApp ordering'})
add(['AI tools','best AI tools','AI tools directory','AI tools Pakistan','AI tools in Pakistan','AI software Pakistan','AI subscriptions Pakistan','AI tools online Pakistan'],'/','Discovery / commercial','home','Existing homepage; clearer supporting architecture','Futurepedia, Toolify, TopAI and AIxploria directory browsing observed','P1','/products/; /categories/; /use-cases/','State marketplace identity and explain how buying works')
add(['AI tools price Pakistan','AI tools pricing Pakistan','AI tools PKR','buy AI subscriptions Pakistan','cheap AI tools Pakistan','AI subscription deals Pakistan','AI software deals Pakistan'],'/pricing/','Commercial comparison','pricing','New; previously prices only on products/home','AI Tools Pak PKR catalog observed','P1','/products/; /guides/choose-ai-subscription/','Show listed prices with non-equivalent durations/access; no invented discount')
add(['AI tools under 1000 PKR'],'/pricing/#under-1000','Budget comparison','pricing','New section, no duplicate budget page','No exact budget SERP verified','P2','/products/','List only catalog matches below the amount')
add(['AI tools under 2000 PKR'],'/pricing/#under-2000','Budget comparison','pricing','New section, no duplicate budget page','No exact budget SERP verified','P2','/products/','List only catalog matches below the amount')
for p in json.loads((ROOT/'data/catalog.json').read_text(encoding='utf-8')):
    add([p['name']+' Pakistan',p['name']+' price Pakistan','buy '+p['name']+' Pakistan',p['name']+' subscription Pakistan',p['name']+' PKR',p['name']+' plan Pakistan'],product_path(p),'Transactional / plan evaluation','product','Existing URL enhanced; slug pinned','AI Tools Pak has product price pages for overlapping brands; exact query position unknown','P1',category_path(p['category'])+'; /guides/private-vs-shared-access/','Exact PKR price + duration + access + availability confirmation')
aliases={'chatgpt-plus':['ChatGPT price Pakistan','ChatGPT Plus price Pakistan','How much does ChatGPT Plus cost in Pakistan?','Is ChatGPT Plus available in Pakistan?'],'gemini-pro':['Gemini price Pakistan'],'canva-pro-edu':['Canva Pro Pakistan','Canva Pro price Pakistan','buy Canva Pro Pakistan'],'figma-pro-private':['Figma Pro Pakistan'],'replit-core':['Replit Pakistan'],'n8n-starter':['n8n Pakistan'],'veo-3-ultra':['Veo 3 Pakistan']}
for slug,keys in aliases.items():add(keys,'/products/'+slug+'/','Commercial / direct question','product','Existing page; no alias URL created','Product intent observed in local marketplace architecture','P1','/pricing/; /categories/','Answer from the seller catalog without asserting official retail equivalence')
category_keywords={'AI Assistants':['AI writing tools','best AI writing tools','AI assistants Pakistan'],'AI Video':['AI video generators','best AI video tools','AI video editing tools Pakistan'],'Design':['AI image generators','AI design tools','AI tools for graphic designers'],'AI Voice':['AI voice generators','AI voice tools Pakistan'],'Development':['AI coding tools','best AI coding tools','AI automation tools'],'Productivity':['AI productivity tools','AI presentation tools'],'VPN & Security':['VPN plans Pakistan'],'Entertainment':['digital entertainment subscriptions Pakistan'],'Business':['professional subscriptions Pakistan'],'Software':['software licenses Pakistan']}
for c in CONTENT['categories']:add(category_keywords[c['name']],category_path(c['name']),'Category discovery','category','New landing page; homepage filters retained','Category taxonomies observed at Futurepedia, Toolify, AIxploria; non-AI categories are local catalog scope','P1','Relevant products; selected use cases and comparisons','Explain the category and how to compare offers')
use_cases={'students':['AI tools for students','AI education tools','AI tools for teachers','AI tools for researchers','What is the best AI tool for students?'],'creators':['AI tools for content creators','AI tools for freelancers','AI tools for YouTubers','AI tools for designers','AI tools for marketers','AI marketing tools'],'developers':['AI tools for developers'],'business':['AI tools for businesses','AI business tools']}
for slug,keys in use_cases.items():add(keys,'/use-cases/ai-tools-for-'+slug+'/','Workflow selection','use-case','New; related audiences consolidated','Task/use-case browsing observed at TopAI; exact audience SERPs not verified','P2','Related categories; selected products; comparisons','Start with the output needed and a practical selection checklist')
for p in CONTENT['pages']:
    if p['type']=='compare':keys=[p['path'].strip('/').split('/')[-1].replace('-',' ')]
    elif p['type']=='alternatives':keys=[p['path'].strip('/').split('/')[-1]+' alternatives']+(['Gemini alternatives'] if 'chatgpt' in p['path'] else [])
    elif p['type']=='guides':keys=['How does AI Tools Zone compare subscriptions?','AI Tools Zone price methodology'] if 'methodology' in p['path'] else (['How do I choose an AI subscription?','How do I buy an AI subscription in Pakistan?'] if 'choose-' in p['path'] else ['What is the difference between private and shared access?','AI subscription invitation meaning'])
    else:continue
    add(keys,p['path'],'Informational / commercial comparison',p['type'],'New original page','AI Tools Pak comparison links and TopAI decision/use-case patterns observed; individual comparisons not assumed covered','P2','; '.join(p['related']),'Direct answer + explicit limitations + catalog table where relevant')
add(['Which AI tool should I use for video editing?'],'/categories/ai-video/','Question','category','New answer','Video taxonomy observed; exact question ranking unknown','P1','/products/capcut-pro/; /compare/capcut-vs-canva/','Distinguish editing existing clips from generation')
add(['Which AI tools are available in Pakistan?','What AI tools can I buy in Pakistan?'],'/products/','Discovery / transaction','catalog','New complete catalog hub','Local PKR marketplace catalogs observed','P1','All products and categories','List offers, then confirm actual availability in chat')
add(['buy AI tools Pakistan','best AI tools Pakistan'],'/','Commercial discovery','home','Existing catalog with task search','Directory discovery observed; localized rankings unknown','P1','/pricing/; /products/')
add(['AI subscriptions price Pakistan','AI tools monthly price Pakistan','AI tools yearly price Pakistan'],'/pricing/','Price comparison','pricing','Existing table retains actual offer durations','Local catalog prices observed','P1','/products/','Explain durations without inventing monthly equivalents')
add(['What payment methods are available?','How long does delivery take?','What warranty is offered?'],'/terms/','Ordering / support','trust','Existing seller terms; exact product values remain on product pages','No competitor policy adopted','P1','/products/; /about/')
seen=set();rows=[r for r in rows if not (r['Keyword'].lower() in seen or seen.add(r['Keyword'].lower()))]
with (ROOT/'SEO-KEYWORD-MAP.csv').open('w',encoding='utf-8',newline='') as f:
    writer=csv.DictWriter(f,fieldnames=list(rows[0]));writer.writeheader();writer.writerows(rows)
print(f'Wrote {len(rows)} intent mappings; search volume, difficulty and rankings remain unknown.')
