"""Exercise every catalog option and regression-test navigation and accessibility."""
from pathlib import Path
import sys, json, threading, http.server, functools
sys.path.insert(0, str(Path(__file__).parent / '.test-deps'))
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).parent
class Handler(http.server.SimpleHTTPRequestHandler):
    def log_message(self,*args): pass
server=http.server.ThreadingHTTPServer(('127.0.0.1',0),functools.partial(Handler,directory=str(ROOT)))
threading.Thread(target=server.serve_forever,daemon=True).start()
url=f'http://127.0.0.1:{server.server_port}'
checks=[]
def check(name, passed):
    checks.append({'name':name,'passed':bool(passed)})
    print(('PASS ' if passed else 'FAIL ')+name,flush=True)
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=r'C:\Program Files\Google\Chrome\Application\chrome.exe',headless=True,args=['--enable-unsafe-swiftshader'])
    page=browser.new_page(viewport={'width':1440,'height':1000})
    errors=[]
    page.on('pageerror',lambda error:errors.append(str(error)))
    page.goto(url,wait_until='networkidle')
    page.emulate_media(reduced_motion='reduce')
    # Original happy-path tests miss these state transitions.
    page.locator('[data-detail="chatgpt"]').first.click()
    page.locator('#modal [data-add]').click()
    check('Add-to-bag feedback is visible in the active dialog',page.evaluate("!!document.querySelector('#modal [role=status]')?.textContent.trim()"))
    check('Product detail offers a direct path to the bag',page.locator('#modal [data-cart]').count()>0)
    page.keyboard.press('Escape')
    page.locator('header [data-cart]').click()
    page.locator('[data-quantity][data-change="1"]').click()
    check('Cart quantity update retains keyboard focus',page.evaluate("document.activeElement.matches('[data-quantity]')"))
    page.keyboard.press('Escape')
    page.locator('footer [data-open-compare]').click()
    check('Compare entry opens a usable selection screen',page.locator('#modal').is_visible())
    if page.locator('#modal').is_visible(): page.keyboard.press('Escape')
    page.locator('#search').fill('ChatGPT')
    page.locator('footer a').filter(has_text='All tools').click()
    check('All tools navigation clears stale filters',page.locator('#search').input_value()=='' and page.locator('.product-card').count()==20)
    page.locator('footer a[href="#refund-policy"]').click()
    page.locator('#refund-policy summary').click()
    page.locator('footer a[href="#refund-policy"]').click()
    check('Repeated refund link always opens the policy',page.locator('#refund-policy').evaluate('e=>e.open'))
    page.locator('#search').fill('')
    page.locator('[data-finder]').first.click()
    page.locator('[name="intent"]').select_option('code')
    page.locator('#finder-form button').click()
    page.locator('.finder-result [data-detail]').first.click()
    check('Finder result details provide a back button',page.locator('[data-modal-back]:visible').count()>0)
    page.keyboard.press('Escape')
    page.set_viewport_size({'width':390,'height':844})
    page.locator('#menu-toggle').click()
    page.keyboard.press('Escape')
    check('Escape resets mobile menu accessible label',page.locator('#menu-toggle').get_attribute('aria-label')=='Open menu')
    if '--baseline' not in sys.argv:
        page.set_viewport_size({'width':1440,'height':1000})
        page.reload(wait_until='networkidle')
        page.emulate_media(reduced_motion='reduce')
        page.locator('#show-more').click()
        catalog=page.evaluate('PRODUCTS')
        from urllib.parse import urlparse,parse_qs
        for product in catalog:
            page.locator(f'[data-detail="{product["id"]}"]').first.click()
            check(f'{product["name"]}: correct detail and WhatsApp order',page.locator('#modal-title').inner_text()==product['name'] and product['name'] in parse_qs(urlparse(page.locator('#modal a[href*="wa.me"]').get_attribute('href')).query)['text'][0])
            page.locator('#modal [data-add]').click()
            check(f'{product["name"]}: add action changes stored bag',page.evaluate('(id)=>JSON.parse(localStorage.getItem("atz-cart-v1"))[id]>0',product['id']))
            page.keyboard.press('Escape')
        for category in dict.fromkeys(item['category'] for item in catalog):
            page.locator(f'[data-category="{category}"]').click()
            check('Category: '+category,page.locator('.product-card').count()==sum(p['category']==category for p in catalog))
        page.locator('[data-category="All tools"]').click()
        for mode,expected in [('price-low',sorted(catalog,key=lambda p:p['price'])),('price-high',sorted(catalog,key=lambda p:-p['price'])),('name',sorted(catalog,key=lambda p:p['name'].lower()))]:
            page.locator('#sort').select_option(mode)
            check('Sorting: '+mode,page.locator('.product-card').evaluate_all('(els)=>els.map(e=>e.dataset.product)')==[p['id'] for p in expected])
        page.locator('#sort').select_option('featured')
        page.locator('#filter-toggle').click()
        for access in ['Private','Shared','Invitation','License Key']:
            page.locator('#access-filter').select_option(access)
            check('Access filter: '+access,page.locator('.product-card').count()==sum(p['access']==access for p in catalog))
        page.locator('#reset-filters').click()
        for intent in ['writing','video','design','code','study','voice','automation','business','entertainment','vpn']:
            page.locator('[data-finder]').first.click()
            page.locator('[name="intent"]').select_option(intent)
            page.locator('[name="budget"]').select_option('any')
            page.locator('#finder-form button').click()
            check('Finder workflow: '+intent,page.locator('.finder-result').count()>0)
            if intent=='video':
                check('Video creation excludes streaming subscriptions',all(name not in page.locator('#modal-content').inner_text() for name in ['Netflix','YouTube Premium']))
            page.keyboard.press('Escape')
        page.locator('[data-finder]').first.click()
        page.locator('[name="intent"]').select_option('voice')
        page.locator('[name="budget"]').select_option('1500')
        page.locator('#finder-form button').click()
        check('Finder empty results remain actionable',page.locator('.finder-result').count()==0 and page.locator('#modal [data-finder]').is_visible())
        page.locator('#modal [data-finder]').click()
        check('Finder retry preserves previous choices',page.locator('[name="intent"]').input_value()=='voice' and page.locator('[name="budget"]').input_value()=='1500')
        page.keyboard.press('Escape')
        page.locator('footer [data-open-compare]').click()
        for id in ['chatgpt','gemini','veo']:
            page.locator(f'#modal [data-compare="{id}"]').check()
        page.locator('#modal [data-compare="leonardo"]').click()
        check('Comparison maximum is enforced',not page.locator('#modal [data-compare="leonardo"]').is_checked())
        page.locator('#modal [data-open-compare]').click()
        check('Three-way comparison renders',page.locator('.compare-table thead th').count()==4)
        page.locator('.compare-table [data-detail]').first.click()
        page.locator('[data-modal-back]').click()
        check('Back from comparison details restores table',page.locator('.compare-table').is_visible())
        page.keyboard.press('Escape')
        page.locator('#clear-compare').click()
        page.locator('[data-privacy]').click()
        page.locator('#clear-local').click()
        check('Privacy action clears bag and confirms visibly',page.evaluate('Object.keys(JSON.parse(localStorage.getItem("atz-cart-v1"))).length')==0 and bool(page.locator('#modal [role=status]').inner_text()))
        page.keyboard.press('Escape')
        page.locator('header [data-cart]').click()
        page.locator('#modal [data-explore]').click()
        check('Empty cart explore takes customer to catalog',page.evaluate('document.activeElement.id')=='search' and not page.locator('#modal').is_visible())
        page.set_viewport_size({'width':390,'height':844})
        page.locator('#menu-toggle').click()
        page.locator('.hero-copy > p').click()
        check('Mobile menu closes on outside click',not page.locator('#main-nav').is_visible())
        page.locator('#motion-toggle').click()
        check('Animation resumes on request',page.locator('#motion-toggle').get_attribute('aria-pressed')=='false')
        page.locator('#motion-toggle').click()
        check('Animation pause works',page.locator('#motion-toggle').get_attribute('aria-pressed')=='true')
        page.locator('[data-detail="chatgpt"]').first.click()
        page.locator('#modal [data-add]').click()
        check('Mobile confirmation does not cover order buttons',page.locator('#modal [role=status]').bounding_box()['y'] >= page.locator('#modal .modal-actions').bounding_box()['y']+page.locator('#modal .modal-actions').bounding_box()['height'])
        page.screenshot(path=str(ROOT/'verification/review-mobile-detail.png'))
        page.locator('#modal [data-cart]').click()
        page.screenshot(path=str(ROOT/'verification/review-mobile-bag.png'))
        check('No JavaScript exceptions during review',not errors)
    browser.close()
server.shutdown()
result={'passed':sum(c['passed'] for c in checks),'failed':sum(not c['passed'] for c in checks),'checks':checks,'errors':errors}
(ROOT/'verification'/('review-baseline.json' if '--baseline' in sys.argv else 'review-results.json')).write_text(json.dumps(result,indent=2),encoding='utf-8')
print(json.dumps({'passed':result['passed'],'failed':result['failed']}))
