"""Browser verification for the local storefront. No WhatsApp messages are sent."""
from pathlib import Path
import sys, json, threading, http.server, functools
sys.path.insert(0, str(Path(__file__).parent / '.test-deps'))
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).parent
OUT = ROOT / 'verification'
OUT.mkdir(exist_ok=True)
class Handler(http.server.SimpleHTTPRequestHandler):
    def log_message(self, *args): pass
server = http.server.ThreadingHTTPServer(('127.0.0.1', 0), functools.partial(Handler, directory=str(ROOT)))
threading.Thread(target=server.serve_forever, daemon=True).start()
url = f'http://127.0.0.1:{server.server_port}'
checks = []
def check(name, condition):
    assert condition, name
    checks.append(name)

with sync_playwright() as p:
    browser = p.chromium.launch(executable_path=r'C:\Program Files\Google\Chrome\Application\chrome.exe', headless=True, args=['--enable-unsafe-swiftshader'])
    page = browser.new_page(viewport={'width':1440,'height':1000}, device_scale_factor=1)
    errors=[]
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.goto(url, wait_until='networkidle')
    page.screenshot(path=str(OUT/'desktop.png'), full_page=True)
    check('20 source products loaded', page.evaluate('PRODUCTS.length') == 20)
    check('8 featured products shown', page.locator('.product-card').count() == 8)
    check('WebGL initialized', page.locator('.no-webgl').count() == 0)
    check('No desktop horizontal overflow', page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
    page.locator('#show-more').click()
    check('All 20 tools expand', page.locator('.product-card').count() == 20)
    page.locator('#search').fill('ChatGPT')
    check('Search selects correct tool', page.locator('.product-card').count() == 1)
    page.locator('[data-add="chatgpt"]').click()
    page.locator('header [data-cart]').click()
    check('Cart total exact', '2,300' in page.locator('.cart-total').inner_text())
    href=page.locator('.cart-checkout').get_attribute('href')
    check('Cart checkout uses correct WhatsApp number', href.startswith('https://wa.me/923136726285?text='))
    check('Cart order includes product details', 'ChatGPT' in href and 'Private' in href)
    page.locator('[data-quantity="chatgpt"][data-change="1"]').click()
    check('Cart quantities recalculate', '4,600' in page.locator('.cart-total').inner_text())
    page.locator('.close-modal').click()
    page.reload(wait_until='networkidle')
    check('Cart persists after reload', page.locator('.cart-count').inner_text() == '2')
    page.locator('header [data-cart]').click()
    page.locator('[data-remove="chatgpt"]').click()
    check('Cart removal and empty state', 'Your bag is empty' in page.locator('#modal-content').inner_text())
    page.locator('.close-modal').click()
    page.locator('[data-compare="chatgpt"]').check()
    page.locator('[data-compare="gemini"]').check()
    page.locator('#compare-bar [data-open-compare]').click()
    check('Comparison lists prices and durations', '18 Months' in page.locator('.compare-table').inner_text() and '2,300' in page.locator('.compare-table').inner_text())
    page.locator('.close-modal').click()
    page.locator('#clear-compare').click()
    page.locator('#filter-toggle').click()
    page.locator('#access-filter').select_option('Private')
    page.locator('#budget-filter').fill('1000')
    check('Combined budget and access filters', page.locator('.product-card').count() == 1 and 'CapCut' in page.locator('.product-card').inner_text())
    page.locator('#reset-filters').click()
    page.locator('[data-finder]').first.click()
    page.locator('[name="intent"]').select_option('code')
    page.locator('[name="budget"]').select_option('3000')
    page.locator('[name="access"]').select_option('Private')
    page.locator('#finder-form button').click()
    check('Finder recommends relevant affordable tools', page.locator('.finder-result').count() >= 1 and 'Lovable Pro' in page.locator('#modal-content').inner_text())
    page.locator('.close-modal').click()
    page.locator('#add-stack').click()
    check('Original four-tool bundle preserved', page.locator('.cart-item').count() == 4 and '7,400' in page.locator('.cart-total').inner_text())
    page.locator('.close-modal').click()
    page.locator('[data-detail="gemini"]').first.click()
    check('Product detail includes original warranty', '30 Days' in page.locator('#modal-content').inner_text())
    page.keyboard.press('Escape')
    check('Escape closes modal', not page.locator('#modal').is_visible())
    page.locator('#search').fill('zzzz-unavailable')
    check('Search empty state is actionable', page.locator('[data-reset]').is_visible())
    page.locator('[data-reset]').click()
    check('All WhatsApp anchors target owner', page.evaluate("[...document.querySelectorAll('a[href*=\"wa.me\"]')].every(a=>a.href.startsWith('https://wa.me/923136726285'))"))
    for width,height in [(1920,1080),(1024,768),(768,1024),(390,844),(360,800)]:
        page.set_viewport_size({'width':width,'height':height})
        page.evaluate('scrollTo(0,0)')
        page.wait_for_timeout(200)
        page.screenshot(path=str(OUT/f'view-{width}.png'), full_page=width in (390,768))
        overflow=page.evaluate("[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1 && getComputedStyle(e).position!=='fixed').map(e=>({tag:e.tagName,cls:e.className,right:Math.round(e.getBoundingClientRect().right),width:Math.round(e.getBoundingClientRect().width)})).slice(0,30)")
        if page.evaluate('document.documentElement.scrollWidth > innerWidth'): print(json.dumps({'overflow_at':width,'elements':overflow}),flush=True)
        check(f'No horizontal overflow at {width}px',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
    page.locator('#menu-toggle').click()
    check('Mobile menu opens',page.locator('#main-nav').is_visible())
    page.locator('#main-nav a').first.click()
    check('Mobile menu closes on navigation',not page.locator('#main-nav').is_visible())
    page.locator('header [data-cart]').click()
    check('Mobile cart fits viewport',page.locator('#modal').bounding_box()['width']<=360)
    page.screenshot(path=str(OUT/'mobile-cart.png'))
    page.keyboard.press('Escape')
    page.emulate_media(reduced_motion='reduce')
    check('Reduced motion respected',page.locator('body').evaluate("el=>el.classList.contains('paused')"))
    check('No JavaScript errors',not errors)
    browser.close()
server.shutdown()
(OUT/'results.json').write_text(json.dumps({'passed':len(checks),'checks':checks,'js_errors':errors},indent=2),encoding='utf-8')
print(json.dumps({'passed':len(checks),'checks':checks,'js_errors':errors},indent=2))
